const {supabaseUrl,supabaseAnonKey,adminEmail}=window.TD_CONFIG;
const client=window.supabase.createClient(supabaseUrl,supabaseAnonKey);
const login=document.querySelector('#login'),dashboard=document.querySelector('#dashboard'),logout=document.querySelector('#logout'),list=document.querySelector('#productList'),editor=document.querySelector('#editor'),form=document.querySelector('#productForm');
let products=[];
const $=id=>document.querySelector(`#${id}`);
function message(id,text,error=false){const el=$(id);el.textContent=text;el.classList.toggle('error',error)}
async function showSession(session){const allowed=session?.user?.email?.toLowerCase()===adminEmail.toLowerCase();login.hidden=allowed;dashboard.hidden=!allowed;logout.hidden=!allowed;if(allowed)await loadProducts();else if(session)message('loginMessage','这个邮箱没有管理员权限。',true)}
$('loginForm').onsubmit=async e=>{e.preventDefault();const email=$('email').value.trim().toLowerCase();if(email!==adminEmail.toLowerCase())return message('loginMessage','请使用 Treasure Depot 管理员邮箱。',true);message('loginMessage','正在发送…');const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/admin.html`}});message('loginMessage',error?`发送失败：${error.message}`:'登录链接已发送，请打开邮箱并点击链接。',!!error)};
logout.onclick=async()=>{await client.auth.signOut();location.reload()};
async function loadProducts(){const {data,error}=await client.from('products').select('*').order('created_at',{ascending:false});if(error)return alert(`读取商品失败：${error.message}`);products=data;renderProducts()}
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderProducts(){$('totalCount').textContent=products.length;$('publishedCount').textContent=products.filter(p=>p.is_published).length;$('lowCount').textContent=products.filter(p=>p.status!=='in_stock').length;list.innerHTML=products.map(p=>`<article class="product-row"><img src="${esc(p.image_url||'')}" alt=""><div><h3>${esc(p.name_zh||p.name_en)}</h3><p>${esc(p.sku)} · $${Number(p.price).toFixed(2)} · 库存 ${p.stock_quantity} · ${p.is_published?'网站展示':'已隐藏'}</p></div><div class="row-actions"><button data-edit="${p.id}">修改</button><button class="delete" data-delete="${p.id}">删除</button></div></article>`).join('')||'<div class="panel">还没有商品，请点击“新增商品”。</div>';list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(products.find(p=>p.id===b.dataset.edit)));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.delete))}
function openEditor(p=null){form.reset();$('productId').value=p?.id||'';$('formTitle').textContent=p?'修改商品':'新增商品';$('published').checked=p?p.is_published:true;if(p){$('sku').value=p.sku;$('category').value=p.category;$('nameEn').value=p.name_en;$('nameZh').value=p.name_zh||'';$('nameEs').value=p.name_es||'';$('descriptionEn').value=p.description_en||'';$('descriptionZh').value=p.description_zh||'';$('descriptionEs').value=p.description_es||'';$('price').value=p.price;$('comparePrice').value=p.compare_at_price||'';$('stock').value=p.stock_quantity;$('status').value=p.status;$('imageUrl').value=p.image_url||'';$('popular').checked=p.is_popular;$('isNew').checked=p.is_new}message('formMessage','');editor.showModal()}
$('newProduct').onclick=()=>openEditor();$('closeEditor').onclick=()=>editor.close();$('cancelEditor').onclick=()=>editor.close();
async function uploadImage(file){if(!file)return $('imageUrl').value.trim()||null;const ext=file.name.split('.').pop().toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const {error}=await client.storage.from('product-images').upload(path,file,{contentType:file.type});if(error)throw error;return client.storage.from('product-images').getPublicUrl(path).data.publicUrl}
form.onsubmit=async e=>{e.preventDefault();message('formMessage','正在保存…');try{const imageUrl=await uploadImage($('image').files[0]);const payload={sku:$('sku').value.trim(),category:$('category').value.trim(),name_en:$('nameEn').value.trim(),name_zh:$('nameZh').value.trim()||null,name_es:$('nameEs').value.trim()||null,description_en:$('descriptionEn').value.trim()||null,description_zh:$('descriptionZh').value.trim()||null,description_es:$('descriptionEs').value.trim()||null,price:Number($('price').value),compare_at_price:$('comparePrice').value?Number($('comparePrice').value):null,stock_quantity:Number($('stock').value),status:$('status').value,image_url:imageUrl,is_popular:$('popular').checked,is_new:$('isNew').checked,is_published:$('published').checked};const id=$('productId').value;const result=id?await client.from('products').update(payload).eq('id',id):await client.from('products').insert(payload);if(result.error)throw result.error;editor.close();await loadProducts()}catch(error){message('formMessage',`保存失败：${error.message}`,true)}};
async function deleteProduct(id){const p=products.find(item=>item.id===id);if(!confirm(`确定删除“${p.name_zh||p.name_en}”吗？`))return;const {error}=await client.from('products').delete().eq('id',id);if(error)return alert(`删除失败：${error.message}`);await loadProducts()}
client.auth.onAuthStateChange((_event,session)=>setTimeout(()=>showSession(session),0));client.auth.getSession().then(({data})=>showSession(data.session));
