let products=[
 {id:'sofa',category:'Furniture',name:'Modular Cloud Sofa',description:'Deep-seat 4-piece modular sofa in easy-clean cream fabric.',price:'$699',old:'$1,099',stock:'In stock',popular:true,image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=85'},
 {id:'fridge',category:'Appliances',name:'French Door Refrigerator',description:'Stainless steel, spacious interior, minor cosmetic packaging marks.',price:'$899',old:'$1,399',stock:'Only 2 left',popular:true,image:'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=1400&q=85'},
 {id:'tires',category:'Auto parts',name:'All-Terrain Tire Set',description:'Set of four 265/70R17 all-terrain tires. Ask staff to confirm fitment.',price:'$520',old:'$760',stock:'In stock',image:'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=1400&q=85'},
 {id:'tools',category:'Industrial',name:'Rolling Tool Cabinet',description:'Heavy-duty 7-drawer steel cabinet with locking casters.',price:'$289',old:'$449',stock:'In stock',image:'https://images.unsplash.com/photo-1581147036324-c1c89c2c8b5c?auto=format&fit=crop&w=1400&q=85'},
 {id:'dining',category:'Furniture',name:'Solid Wood Dining Set',description:'Six-seat warm oak dining table set, warehouse assembled sample.',price:'$449',old:'$699',stock:'Only 1 left',image:'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1400&q=85'},
 {id:'washer',category:'Appliances',name:'Front Load Washer',description:'High-efficiency washer with steam cycle. Sold as-is after inspection.',price:'$399',old:'$649',stock:'Sold out',image:'https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?auto=format&fit=crop&w=1400&q=85'}
];
const categoryKeys=['all','new','favorites','Furniture','Appliances','Auto parts','Industrial','General merchandise','Fitness','Pet supplies','Kitchen','Outdoor'];
const translations={
 en:{topInventory:'● WAREHOUSE INVENTORY',topNotice:'Updated daily · In-store purchase only',navInventory:'Inventory',navVisit:'Visit us',favorites:'♥ My favorites',heroEyebrow:'LOCAL DEALS · REAL INVENTORY',heroTitle:'Find it online.<br>Pick it up today.',heroLead:'New arrivals, open-box deals, and warehouse prices. Browse before you drive—then inspect and buy in person.',browse:'Browse inventory ↓',directions:'Get directions ↗',checkInspect:'✓ Inspect before buying',checkDelivery:'✓ Delivery temporarily unavailable',checkTeam:'✓ Friendly local team',thisWeek:'THIS WEEK',newLoads:'New loads arriving daily',followFirst:'Follow us for first look →',inventoryEyebrow:'WAREHOUSE INVENTORY',floorTitle:'What’s on the floor',empty:'No matching products. Try another search or category.',visitEyebrow:'VISIT THE WAREHOUSE',visitTitle:'See it. Test it.<br>Take it home.',visitLead:'Inventory changes quickly. Call before driving for limited-stock items.',addressLabel:'Warehouse address',hoursLabel:'Business hours',hoursValue:'Mon–Sat 9:00 AM–6:00 PM<br>Sun 10:00 AM–4:00 PM',phoneLabel:'Phone',callWarehouse:'Call warehouse',socialEyebrow:'SEE TODAY’S ARRIVALS',socialTitle:'Follow the next truckload.',socialLead:'Follow for new truckloads, walk-through videos, and flash deals.',footer:'© 2026 treasuredepotva.com · Prices and availability subject to change.',dialogNotice:'Visit the warehouse to inspect this item and confirm availability before purchasing.',search:'Search products…',count:n=>`${n} item${n===1?'':'s'} available`,popular:'POPULAR',saveFavorite:'Save favorite',viewItem:'View item',categories:{all:'All products',new:'✦ New arrivals',favorites:'♥ My favorites',Furniture:'Furniture',Appliances:'Appliances','Auto parts':'Auto parts',Industrial:'Industrial','General merchandise':'General merchandise',Fitness:'Fitness','Pet supplies':'Pet supplies',Kitchen:'Kitchen',Outdoor:'Outdoor'},stock:{'In stock':'In stock','Only 2 left':'Only 2 left','Only 1 left':'Only 1 left','Sold out':'Sold out'}},
 zh:{topInventory:'● 仓库实时库存',topNotice:'每日更新 · 仅限到店购买',navInventory:'商品库存',navVisit:'到店信息',favorites:'♥ 我的收藏',heroEyebrow:'本地优惠 · 真实库存',heroTitle:'网上先挑选，<br>今天就能取货。',heroLead:'新品、开箱商品和仓库特价。出发前先在线浏览，到店检查满意后再购买。',browse:'浏览库存 ↓',directions:'获取路线 ↗',checkInspect:'✓ 购买前可现场检查',checkDelivery:'✓ 暂不提供送货服务',checkTeam:'✓ 友好的本地服务团队',thisWeek:'本周到货',newLoads:'每天都有新货入库',followFirst:'关注我们，抢先查看 →',inventoryEyebrow:'仓库实时库存',floorTitle:'当前在售商品',empty:'没有找到匹配商品，请尝试其他关键词或分类。',visitEyebrow:'欢迎到店选购',visitTitle:'现场看，现场试，<br>满意就带回家。',visitLead:'库存变化较快。数量有限的商品，建议出发前先致电确认。',addressLabel:'仓库地址',hoursLabel:'营业时间',hoursValue:'周一至周六 9:00–18:00<br>周日 10:00–16:00',phoneLabel:'联系电话',callWarehouse:'致电仓库',socialEyebrow:'查看今日新品',socialTitle:'关注下一批到货。',socialLead:'关注我们的新货、仓库实拍视频和限时优惠。',footer:'© 2026 treasuredepotva.com · 价格与库存可能随时变动。',dialogNotice:'购买前请到仓库现场检查商品并确认库存。',search:'搜索商品…',count:n=>`现有 ${n} 件商品`,popular:'热门',saveFavorite:'收藏商品',viewItem:'查看商品',categories:{all:'全部商品',new:'✦ 最新到货',favorites:'♥ 我的收藏',Furniture:'家具',Appliances:'家用电器','Auto parts':'汽车配件',Industrial:'工业用品','General merchandise':'日用百货',Fitness:'健身器材','Pet supplies':'宠物用品',Kitchen:'厨房用品',Outdoor:'户外用品'},stock:{'In stock':'现货','Only 2 left':'仅剩 2 件','Only 1 left':'仅剩 1 件','Sold out':'已售罄'}},
 es:{topInventory:'● INVENTARIO DEL ALMACÉN',topNotice:'Actualizado a diario · Compra solo en tienda',navInventory:'Inventario',navVisit:'Visítanos',favorites:'♥ Mis favoritos',heroEyebrow:'OFERTAS LOCALES · INVENTARIO REAL',heroTitle:'Encuéntralo en línea.<br>Recógelo hoy.',heroLead:'Novedades, productos de caja abierta y precios de almacén. Mira el inventario antes de venir, inspecciona el artículo y cómpralo en persona.',browse:'Ver inventario ↓',directions:'Cómo llegar ↗',checkInspect:'✓ Inspecciona antes de comprar',checkDelivery:'✓ Entrega no disponible temporalmente',checkTeam:'✓ Equipo local y atento',thisWeek:'ESTA SEMANA',newLoads:'Mercancía nueva todos los días',followFirst:'Síguenos para verla primero →',inventoryEyebrow:'INVENTARIO DEL ALMACÉN',floorTitle:'Disponible en el almacén',empty:'No encontramos productos. Prueba otra búsqueda o categoría.',visitEyebrow:'VISITA EL ALMACÉN',visitTitle:'Míralo. Pruébalo.<br>Llévatelo a casa.',visitLead:'El inventario cambia rápidamente. Llama antes de venir por artículos con pocas unidades.',addressLabel:'Dirección del almacén',hoursLabel:'Horario',hoursValue:'Lun–Sáb 9:00–18:00<br>Dom 10:00–16:00',phoneLabel:'Teléfono',callWarehouse:'Llamar al almacén',socialEyebrow:'MIRA LAS NOVEDADES DE HOY',socialTitle:'Sigue la próxima carga.',socialLead:'Síguenos para ver mercancía nueva, videos del almacén y ofertas relámpago.',footer:'© 2026 treasuredepotva.com · Los precios y la disponibilidad pueden cambiar.',dialogNotice:'Visita el almacén para inspeccionar el artículo y confirmar su disponibilidad antes de comprar.',search:'Buscar productos…',count:n=>`${n} producto${n===1?'':'s'} disponible${n===1?'':'s'}`,popular:'POPULAR',saveFavorite:'Guardar favorito',viewItem:'Ver producto',categories:{all:'Todos los productos',new:'✦ Recién llegados',favorites:'♥ Mis favoritos',Furniture:'Muebles',Appliances:'Electrodomésticos','Auto parts':'Repuestos para autos',Industrial:'Equipo industrial','General merchandise':'Mercancía general',Fitness:'Ejercicio','Pet supplies':'Artículos para mascotas',Kitchen:'Cocina',Outdoor:'Exterior'},stock:{'In stock':'Disponible','Only 2 left':'Solo quedan 2','Only 1 left':'Solo queda 1','Sold out':'Agotado'}}
};
const productTranslations={zh:{sofa:['组合式云朵沙发','四件套深座组合沙发，奶油色面料，易于清洁。'],fridge:['法式对开门冰箱','不锈钢外观，内部空间宽敞，包装留下轻微外观痕迹。'],tires:['全地形轮胎套装','四条 265/70R17 全地形轮胎。请让工作人员确认是否适配您的车辆。'],tools:['移动式工具柜','重型七抽屉钢制工具柜，配有可锁定脚轮。'],dining:['实木餐桌椅套装','暖橡木色六人餐桌椅套装，仓库组装展示样品。'],washer:['前置式洗衣机','高效节能洗衣机，带蒸汽洗涤功能。检查后按现状出售。']},es:{sofa:['Sofá modular tipo nube','Sofá modular de 4 piezas, asiento profundo y tela color crema fácil de limpiar.'],fridge:['Refrigerador de puertas francesas','Acero inoxidable, interior amplio y pequeñas marcas cosméticas del embalaje.'],tires:['Juego de llantas todoterreno','Juego de cuatro llantas todoterreno 265/70R17. Consulta al personal para confirmar la compatibilidad.'],tools:['Gabinete móvil para herramientas','Gabinete de acero resistente con 7 cajones y ruedas con bloqueo.'],dining:['Juego de comedor de madera maciza','Mesa y seis sillas en roble cálido; muestra ensamblada en el almacén.'],washer:['Lavadora de carga frontal','Lavadora de alta eficiencia con ciclo de vapor. Se vende tal como está después de la inspección.']}};
let active='all';let query='';let language=localStorage.getItem('td-language')||'en';if(!translations[language])language='en';const saved=new Set(JSON.parse(localStorage.getItem('td-favorites')||'[]'));
const grid=document.querySelector('#productGrid'),filters=document.querySelector('#filters'),count=document.querySelector('#itemCount'),empty=document.querySelector('#empty'),favHeader=document.querySelector('.favorite-count');
function t(){return translations[language]}
function localizedProduct(p){const translated=p.dbTranslations?.[language]||productTranslations[language]?.[p.id];return {...p,name:translated?.[0]||p.name,description:translated?.[1]||p.description,category:t().categories[p.category]||p.category,stock:t().stock[p.stock]||p.stock}}
function save(){localStorage.setItem('td-favorites',JSON.stringify([...saved]));favHeader.textContent=saved.size;renderFilters()}
function renderFilters(){filters.innerHTML=categoryKeys.map(c=>`<button class="${c===active?'active':''}" data-category="${c}">${t().categories[c]}${c==='favorites'?` (${saved.size})`:''}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.category;render()})}
function matches(p){const q=query.toLowerCase();const lp=localizedProduct(p);const text=`${p.name} ${p.description} ${p.category} ${lp.name} ${lp.description} ${lp.category}`.toLowerCase();if(q&&!text.includes(q))return false;if(active==='all')return true;if(active==='new')return p.stock!=='Sold out';if(active==='favorites')return saved.has(p.id);return p.category===active}
function render(){renderFilters();const list=products.filter(matches);count.textContent=t().count(list.length);empty.hidden=list.length>0;grid.innerHTML=list.map(original=>{const p=localizedProduct(original);return `<article class="card"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="stock">${p.stock}</span><button class="fav ${saved.has(p.id)?'saved':''}" data-fav="${p.id}" aria-label="${t().saveFavorite}: ${p.name}">${saved.has(p.id)?'♥':'♡'}</button><div class="card-body"><span class="tag">${p.popular?t().popular+' · ':''}${p.category}</span><h3>${p.name}</h3><p>${p.description}</p><div class="price"><strong>${p.price}</strong><del>${p.old}</del></div></div><button class="view" data-view="${p.id}" aria-label="${t().viewItem}: ${p.name}">→</button></article>`}).join('');grid.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{saved.has(b.dataset.fav)?saved.delete(b.dataset.fav):saved.add(b.dataset.fav);save();render()});grid.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openProduct(products.find(p=>p.id===b.dataset.view)))}
function openProduct(original){const p=localizedProduct(original);const d=document.querySelector('#productDialog');document.querySelector('#dialogImage').src=p.image;document.querySelector('#dialogImage').alt=p.name;document.querySelector('#dialogCategory').textContent=p.category;document.querySelector('#dialogTitle').textContent=p.name;document.querySelector('#dialogDescription').textContent=p.description;document.querySelector('#dialogPrice').textContent=`${p.price}  ·  ${p.stock}`;d.showModal()}
function applyLanguage(){document.documentElement.lang=language==='zh'?'zh-CN':language;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t()[el.dataset.i18n]);document.querySelectorAll('[data-i18n-html]').forEach(el=>el.innerHTML=t()[el.dataset.i18nHtml]);const search=document.querySelector('#search');search.placeholder=t().search;search.setAttribute('aria-label',t().search);document.querySelector('#language').value=language;localStorage.setItem('td-language',language);render()}
function mapDatabaseProduct(p){
 const stock=p.status==='sold_out'?'Sold out':p.status==='low_stock'?`Only ${p.stock_quantity} left`:'In stock';
 return {id:p.id,category:p.category,name:p.name_en,description:p.description_en,price:`$${Number(p.price).toFixed(2)}`,old:p.compare_at_price?`$${Number(p.compare_at_price).toFixed(2)}`:'',stock,popular:p.is_popular,image:p.image_url||'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=85',dbTranslations:{zh:[p.name_zh,p.description_zh],es:[p.name_es,p.description_es]}};
}
async function loadProducts(){
 try{
  const {supabaseUrl,supabaseAnonKey}=window.TD_CONFIG;
  const response=await fetch(`${supabaseUrl}/rest/v1/products?select=*&is_published=eq.true&order=created_at.desc`,{headers:{apikey:supabaseAnonKey,Authorization:`Bearer ${supabaseAnonKey}`}});
  if(!response.ok)throw new Error('Inventory unavailable');
  const rows=await response.json();
  if(rows.length)products=rows.map(mapDatabaseProduct);
 }catch(error){console.warn('Using backup inventory:',error.message)}
 render();
}
document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;render()});document.querySelector('#favorites').onclick=()=>{active='favorites';document.querySelector('#inventory').scrollIntoView();render()};document.querySelector('#productDialog .close').onclick=()=>document.querySelector('#productDialog').close();document.querySelector('#productDialog').onclick=e=>{if(e.target.id==='productDialog')e.target.close()};
document.querySelector('#language').onchange=e=>{language=e.target.value;applyLanguage()};
save();applyLanguage();loadProducts();
