const products=[
 {id:'sofa',category:'Furniture',name:'Modular Cloud Sofa',description:'Deep-seat 4-piece modular sofa in easy-clean cream fabric.',price:'$699',old:'$1,099',stock:'In stock',popular:true,image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=85'},
 {id:'fridge',category:'Appliances',name:'French Door Refrigerator',description:'Stainless steel, spacious interior, minor cosmetic packaging marks.',price:'$899',old:'$1,399',stock:'Only 2 left',popular:true,image:'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=1400&q=85'},
 {id:'tires',category:'Auto parts',name:'All-Terrain Tire Set',description:'Set of four 265/70R17 all-terrain tires. Ask staff to confirm fitment.',price:'$520',old:'$760',stock:'In stock',image:'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=1400&q=85'},
 {id:'tools',category:'Industrial',name:'Rolling Tool Cabinet',description:'Heavy-duty 7-drawer steel cabinet with locking casters.',price:'$289',old:'$449',stock:'In stock',image:'https://images.unsplash.com/photo-1581147036324-c1c89c2c8b5c?auto=format&fit=crop&w=1400&q=85'},
 {id:'dining',category:'Furniture',name:'Solid Wood Dining Set',description:'Six-seat warm oak dining table set, warehouse assembled sample.',price:'$449',old:'$699',stock:'Only 1 left',image:'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1400&q=85'},
 {id:'washer',category:'Appliances',name:'Front Load Washer',description:'High-efficiency washer with steam cycle. Sold as-is after inspection.',price:'$399',old:'$649',stock:'Sold out',image:'https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?auto=format&fit=crop&w=1400&q=85'}
];
const categories=['All products','✦ New arrivals','♥ My favorites','Furniture','Appliances','Auto parts','Industrial','General merchandise','Fitness','Pet supplies','Kitchen','Outdoor'];
let active='All products';let query='';const saved=new Set(JSON.parse(localStorage.getItem('td-favorites')||'[]'));
const grid=document.querySelector('#productGrid'),filters=document.querySelector('#filters'),count=document.querySelector('#itemCount'),empty=document.querySelector('#empty'),favHeader=document.querySelector('#favorites span');
function save(){localStorage.setItem('td-favorites',JSON.stringify([...saved]));favHeader.textContent=saved.size;renderFilters()}
function renderFilters(){filters.innerHTML=categories.map(c=>`<button class="${c===active?'active':''}" data-category="${c}">${c}${c==='♥ My favorites'?` (${saved.size})`:''}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.category;render()})}
function matches(p){const q=query.toLowerCase();const text=`${p.name} ${p.description} ${p.category}`.toLowerCase();if(q&&!text.includes(q))return false;if(active==='All products')return true;if(active==='✦ New arrivals')return p.stock!=='Sold out';if(active==='♥ My favorites')return saved.has(p.id);return p.category===active}
function render(){renderFilters();const list=products.filter(matches);count.textContent=`${list.length} item${list.length===1?'':'s'} available`;empty.hidden=list.length>0;grid.innerHTML=list.map(p=>`<article class="card"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="stock">${p.stock}</span><button class="fav ${saved.has(p.id)?'saved':''}" data-fav="${p.id}" aria-label="Save favorite: ${p.name}">${saved.has(p.id)?'♥':'♡'}</button><div class="card-body"><span class="tag">${p.popular?'POPULAR · ':''}${p.category}</span><h3>${p.name}</h3><p>${p.description}</p><div class="price"><strong>${p.price}</strong><del>${p.old}</del></div></div><button class="view" data-view="${p.id}" aria-label="View item: ${p.name}">→</button></article>`).join('');grid.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{saved.has(b.dataset.fav)?saved.delete(b.dataset.fav):saved.add(b.dataset.fav);save();render()});grid.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openProduct(products.find(p=>p.id===b.dataset.view)))}
function openProduct(p){const d=document.querySelector('#productDialog');document.querySelector('#dialogImage').src=p.image;document.querySelector('#dialogImage').alt=p.name;document.querySelector('#dialogCategory').textContent=p.category;document.querySelector('#dialogTitle').textContent=p.name;document.querySelector('#dialogDescription').textContent=p.description;document.querySelector('#dialogPrice').textContent=`${p.price}  ·  ${p.stock}`;d.showModal()}
document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;render()});document.querySelector('#favorites').onclick=()=>{active='♥ My favorites';document.querySelector('#inventory').scrollIntoView();render()};document.querySelector('#productDialog .close').onclick=()=>document.querySelector('#productDialog').close();document.querySelector('#productDialog').onclick=e=>{if(e.target.id==='productDialog')e.target.close()};
document.querySelector('#language').onchange=e=>{if(e.target.value==='zh')alert('中文版本即将推出。当前商品与价格保持英文显示。');if(e.target.value==='es')alert('La versión en español estará disponible pronto.');e.target.value='en'};
save();render();
